apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: busybox
  name: busybox
spec:
  securityContext:
    runAsUser: 2000
    fsGroup: 3000
  containers:
  - image: busybox
    name: busybox
    resources: {}
    command: ['sh','-c','cat /messages/hello.txt && cat /messages/bye.txt && sleep 3600']
    volumeMounts:
    - name: messages
      mountPath: /messages
  volumes:
  - name: messages
    hostPath: 
      path: /etc/messages
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
