apiVersion: v1
kind: Pod
metadata:
  name: secret-message-pod
  labels:
    app: busybox-secret-pod
    uses: secret
spec:
  containers:
  - image: busybox
    name: busybox
    command: ['sh', '-c', 'echo $SECRET && sleep 3600;']
    env:
    - name: SECRET
      valueFrom:
        secretKeyRef:
          name: my-secrets
          key: myKey 

