apiVersion: v1
kind: Pod
metadata:
  namespace: os # kubectl create namespace os 
  name: busybox
  labels:
    app: busybox
    uses: command
spec:
  serviceAccountName: busybox-serviceaccount
  containers:
  - image: busybox
    name: busybox
    command: ['sh','-c','echo "${MESSAGE}. Uses ServiceAccount." && sleep 3600']
    env:
    - name: MESSAGE
      valueFrom:
        secretKeyRef:
          name: busybox-secret
          key: message
