apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: busybox
  name: busybox
spec:
  securityContext:
    runAsUser: 2000
    fsGroup: 3000
  containers:
  - image: busybox
    name: busybox
    resources: {}
    command: ['sh','-c','echo "Hello, BusyBoss" && sleep 3600']
    resources:
      requests:
        memory: '64Mi'
        cpu: '250m'
      limits:
        memory: '128Mi'
        cpu: '500m'
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
