apiVersion: v1
kind: Pod
metadata:
  namespace: os # kubectl create namespace os 
  name: busybox
  labels:
    app: busybox
    uses: command
spec:
  containers:
  - image: busybox
    name: busybox
    command: ['sh','-c','echo "Hello, Kubernetes Namespace" && sleep 3600']

